# Jekyll config for
# https://github.com/runxel/rhino-secrets
prettyname: Rhino Secrets ğŸ¦
theme: minima
# https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
baseurl: /rhino-secrets
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  