# Jekyll config for
# https://github.com/runxel/rhino-secrets
prettyname: Rhino Secrets ğŸ¦
theme: minima
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  